# Generated by Django 4.2.1 on 2023-05-29 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drivingschool", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackOfCourseHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("number_of_hours", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LessonsTaken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("effective", models.BooleanField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("commentary", models.TextField(blank=True, null=True)),
                (
                    "customuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
