# Generated by Django 4.2.1 on 2023-06-03 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drivingschool", "0003_packofcoursehours_lessonstaken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonstaken",
            name="customuser",
        ),
        migrations.DeleteModel(
            name="PackOfCourseHours",
        ),
        migrations.DeleteModel(
            name="LessonsTaken",
        ),
    ]
