# Generated by Django 4.2.1 on 2023-06-04 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("title", models.CharField(max_length=200, blank=True, null=True)),
                ("text", models.TextField(max_length=200, blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("cover", models.ImageField(blank=True, upload_to="covers/")),
            ],
            options={
                "permissions": [("special_status", "Can read all lessons")],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.CharField(max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="lessons.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonsTaken",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("effective", models.BooleanField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("commentary", models.TextField(blank=True, null=True)),
                (
                    "customuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["id"], name="id_index"),
        ),
    ]
